version: "3.8"

services:

  stunnel:
    image: k44sh/stunnel
    container_name: stunnel
    hostname: stunnel
    restart: unless-stopped
    networks:
      - stunnel
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}/tcp"
    volumes:
      - stunnel:/etc/stunnel
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    env_file:
      - .env

### Networks
networks:
  stunnel:
    name: stunnel

### Configurations
volumes:
  stunnel:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./stunnel"
